# Generated by Django 2.2.8 on 2019-12-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('import_name', models.CharField(max_length=100)),
                ('common_short_hand', models.CharField(blank=True, max_length=100, null=True)),
                ('current_version', models.CharField(blank=True, max_length=100, null=True)),
                ('is_base_package', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'db_table': 'appadmin_packages',
                'ordering': ['package_name'],
            },
        ),
    ]
